# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Testtesttest
tagline:          'This will be something at some point'
description:      'I'm gonna leave these <a href="http://jekyllrb.com" target="_blank">Links</a> here so I remember how to do them.
url:              http://github.com/poole/hyde
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
